[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
  [plugins.build]
    mac   = 'make'
    linux = 'make'
    unix  = 'gmake'

# LSP
# https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = '0'
rev = 'release'
build = 'yarn install --frozen-lockfile'

[[plugins]]
repo = 'kevinoid/vim-jsonc'

# ruby, rails
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'basyura/unite-rails'
on_ft = 'ruby'

# elixir
[[plugins]]
repo = 'elixir-lang/vim-elixir'
on_ft = 'elixir'

[[plugins]]
repo = 'mattreduce/vim-mix'
on_ft = 'elixir'

# golang
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

# Rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

# Haskell
[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = 'haskell'

[[plugins]]
repo = 'dag/vim2hs'
on_ft = 'haskell'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = 'haskell'

[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = 'haskell'

# front-end
[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = 'scss'

[[plugins]]
repo = 'lilydjwg/colorizer'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo = 'tpope/vim-haml'
on_ft = 'haml'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]]
repo = 'ElmCast/elm-vim'
on_ft = 'elm'

# Text
[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = 'md'

# 補完
[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# status line
[[plugins]]
repo = 'itchyny/lightline.vim'

# color scheme
[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'EdenEast/nightfox.nvim'

# others
[[plugins]]
repo = 'Toruiwashita/git-switcher.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'thinca/vim-quickrun'

# 表示
[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = "jiangmiao/auto-pairs"

[[plugins]]
repo = "airblade/vim-gitgutter"

# Tags
[[plugins]]
repo = 'szw/vim-tags'
